routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('project', 'ProjectController', ['only' => ['create', 'edit', 'store', 'update']]);

app/Project.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['name', 'description', 'price', 'start_date', 'end_date', 'done_tasks'];

    protected $dates = ['start_date', 'end_date'];

    public function setUsersAttribute($value)
    {
        $this->users()->sync($value);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function getUserIdsAttribute()
    {
        return $this->users->pluck('id')->toArray();
    }

    public function getStartDateAttribute($value)
    {
        $time = new Carbon($value);
        return $time->format('Y-m-d');
    }

    public function getEndDateAttribute($value)
    {
        $time = new Carbon($value);
        return $time->format('Y-m-d');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function owned_projects()
    {
        return $this->hasMany(Project::class, 'user_id');
    }

    public function projects()
    {
        return $this->belongsToMany(Project::class, 'project_user');
    }

    public function isOwnerOf(Model $model, $foreignKey = 'user_id')
    {
        return $this->id == $model->$foreignKey;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'price' => 'required|numeric',
            'description' => 'required',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
            'user_ids.*' => 'integer|exists:users,id',
        ]);

        $data = $request->all();
        $project = auth()->user()->owned_projects()->create($data);
        if(isset($data['user_ids']) && is_array($data['user_ids']))
            $project->users()->sync($data['user_ids']);

        return redirect()->route('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        if(auth()->user()->isOwnerOf($project)){
            $this->validate($request, [
                'name' => 'required',
                'price' => 'required|numeric',
                'description' => 'required',
                'start_date' => 'required|date',
                'end_date' => 'required|date',
                'user_ids.*' => 'integer|exists:users,id',
            ]);
        }

        $data = $request->all();

        $project->update($data);
        if(isset($data['user_ids']) && is_array($data['user_ids']))
            $project->users()->sync($data['user_ids']);

        return redirect()->route('project.edit', $project);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/errors.blade.php
@if ($errors->any())
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        {!! $error !!}<br/>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@elseif (session()->get('flash_success'))
    <div class="alert alert-success">
        @if(is_array(json_decode(session()->get('flash_success'), true)))
            {!! implode('', session()->get('flash_success')->all(':message<br/>')) !!}
        @else
            {!! session()->get('flash_success') !!}
        @endif
    </div>
@elseif (session()->get('flash_warning'))
    <div class="alert alert-warning">
        @if(is_array(json_decode(session()->get('flash_warning'), true)))
            {!! implode('', session()->get('flash_warning')->all(':message<br/>')) !!}
        @else
            {!! session()->get('flash_warning') !!}
        @endif
    </div>
@elseif (session()->get('flash_info'))
    <div class="alert alert-info">
        @if(is_array(json_decode(session()->get('flash_info'), true)))
            {!! implode('', session()->get('flash_info')->all(':message<br/>')) !!}
        @else
            {!! session()->get('flash_info') !!}
        @endif
    </div>
@elseif (session()->get('flash_danger'))
    <div class="alert alert-danger">
        @if(is_array(json_decode(session()->get('flash_danger'), true)))
            {!! implode('', session()->get('flash_danger')->all(':message<br/>')) !!}
        @else
            {!! session()->get('flash_danger') !!}
        @endif
    </div>
@elseif (session()->get('flash_message'))
    <div class="alert alert-info">
        @if(is_array(json_decode(session()->get('flash_message'), true)))
            {!! implode('', session()->get('flash_message')->all(':message<br/>')) !!}
        @else
            {!! session()->get('flash_message') !!}
        @endif
    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    <div>
                        <a href="{{ route('project.create') }}" class="btn btn-primary">Add new project</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Projects</div>

            <div class="panel-body">
                <div class="col-md-6">
                    <h3>My projects</h3>

                    <ul>
                        @foreach(auth()->user()->owned_projects as $project)
                            <li><a href="{{ route('project.edit', $project) }}">{{ $project->name }}</a></li>
                        @endforeach
                    </ul>
                </div>

                <div class="col-md-6">
                    <h3>Projects I'm part of</h3>

                    <ul>
                        @foreach(auth()->user()->projects as $project)
                            <li><a href="{{ route('project.edit', $project) }}">{{ $project->name }}</a></li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @include('errors')

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create new project</div>

                    <div class="panel-body">
                        {!! Form::open(['route' => 'project.store']) !!}

                        <div class="form-group">
                            <label for="name">Name</label>
                            {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'required']) !!}
                        </div>

                        <div class="form-group">
                            <label for="description">Description</label>
                            {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'description', 'required']) !!}
                        </div>

                        <div class="form-group">
                            <label for="price">Price</label>
                            {!! Form::number('price', null, ['class' => 'form-control', 'id' => 'price', 'step' => 0.01, 'required']) !!}
                        </div>

                        <div class="form-group">
                            <label for="user_ids">Users</label>
                            {!! Form::select('user_ids[]', \App\User::where('id', '<>', auth()->user()->id)->get()->pluck('name', 'id'), null, ['class' => 'form-control','multiple' => true]) !!}
                        </div>

                        <div class="form-group">
                            <label for="start_date">Start date</label>
                            {!! Form::date('start_date', null, ['class' => 'form-control', 'id' => 'start_date', 'required']) !!}
                        </div>

                        <div class="form-group">
                            <label for="end_date">End date</label>
                            {!! Form::date('end_date', null, ['class' => 'form-control', 'id' => 'end_date', 'required']) !!}
                        </div>

                        <div class="form-group">
                            <div class="clearfix">

                                <div class="pull-right">
                                    {!! Form::submit('Create', ['class' => 'btn btn-primary']) !!}
                                </div>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit project</div>

                    <div class="panel-body">
                        {!! Form::model($project, ['route' => ['project.update', $project], 'method' => 'PUT']) !!}

                        @if(auth()->user()->isOwnerOf($project))
                            <div class="form-group">
                                <label for="name">Name</label>
                                {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'required']) !!}
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'description', 'required']) !!}
                            </div>

                            <div class="form-group">
                                <label for="price">Price</label>
                                {!! Form::number('price', null, ['class' => 'form-control', 'id' => 'price', 'step' => 0.01, 'required']) !!}
                            </div>

                            <div class="form-group">
                                <label for="user_ids">Users</label>
                                {!! Form::select('user_ids[]', \App\User::where('id', '<>', auth()->user()->id)->get()->pluck('name', 'id'), $project->user_ids, ['class' => 'form-control','multiple' => true]) !!}
                            </div>

                            <div class="form-group">
                                <label for="start_date">Start date</label>
                                {!! Form::date('start_date', null, ['class' => 'form-control', 'id' => 'start_date', 'required']) !!}
                            </div>

                            <div class="form-group">
                                <label for="end_date">End date</label>
                                {!! Form::date('end_date', null, ['class' => 'form-control', 'id' => 'end_date', 'required']) !!}
                            </div>

                        @else
                            <dl class="dl-horizontal">
                                <dt>Name</dt>
                                <dd>{{ $project->name }}</dd>

                                <dt>Price</dt>
                                <dd>{{ $project->price }}</dd>

                                <dt>Description</dt>
                                <dd>{{ $project->description }}</dd>

                                <dt>Owner</dt>
                                <dd>{{ $project->owner->name }}</dd>

                                <dt>Start date</dt>
                                <dd>{{ $project->start_date }}</dd>

                                <dt>End date</dt>
                                <dd>{{ $project->end_date }}</dd>

                                <dt>Users</dt>
                                <dd>
                                    <ul>
                                        @foreach($project->users as $user)
                                        <li>{{ $user->name }}</li>
                                        @endforeach
                                    </ul>
                                </dd>
                            </dl>
                        @endif

                        <div class="form-group">
                            <label for="done_tasks">Done tasks</label>
                            {!! Form::textarea('done_tasks', null, ['class' => 'form-control', 'id' => 'done_tasks']) !!}
                        </div>

                        <div class="form-group">
                            <div class="clearfix">

                                <div class="pull-right">
                                    {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
                                </div>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection